### ISSUE TITLE
Infografia Jose Ricardo Mendez Barrios 1AS

### ISSUE THREAD

**Issue by RichiMB** [SistemasTecTlaxiaco/infografia-RichiMB#2]
[Jose Ricardo Mendez Barrios 1AS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-RichiMB/files/7174909/Jose.Ricardo.Mendez.Barrios.1AS.pdf)

**Comment by Arlet04** [comment]
Redacción y ortografía (evidencia adecuada) contiene errores de acentuación por lo que hay revisar bien la ortografía (2 puntos)
Exposición de ideas centrales (evidencia clara y precisa) tiene buena síntesis ( 3 puntos )
organización de la información (evidencia clara y detallada) es breve la información y clara  (3 puntos)
uso de imágenes y colores (evidencia clara y detallada) contiene suficientes imágenes  (3 puntos)
presentación visual (alguna evidencia) falta implementar colores e ideas llamativas  (2 puntos)
Referencias (evidencia clara y detallada) emplea las fuentes de donde se adquirió la información (3 puntos)
Presentación (evidencia clara y detallada) realizó la entrega en tiempo y de forma adecuada (3)
Total: 19/21
calificación:18.09 % /20%
calificado por: Jeanette Arlet Salazar Nicolás

**Comment by josealfredo79** [comment]
Bien hecho y revisado
